### ISSUE TITLE
An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

### ISSUE THREAD

**Issue by justinvp** [pulumi/actions-pulumify#8]
Pulumify failed for this PR: https://github.com/pulumi/docs/pull/2485

```
2020-02-20T04:43:26.8338490Z  +  pulumi:pulumi:Stack pulumify-pulumify-pulumi-docs-justin-purge creating Error: Invoking sync function 'arn:aws:lambda:us-east-1:894850187425:function:content-syncer-copyfunc-8c64fd3' failed [Unhandled]: "{\"errorMessage\": \"An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\", \"errorType\": \"NoSuchKey\", \"stackTrace\": [\"  File \\\"/var/task/index.py\\\", line 42, in handler\\n    archive_bytes = io.BytesIO(s3.meta.client.get_object(Bucket=bucket, Key=archive_key)['Body'].read())\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 357, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 661, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
2020-02-20T04:43:26.8339512Z  +  pulumi:pulumi:Stack pulumify-pulumify-pulumi-docs-justin-purge creating     at Object.<anonymous> (<anonymous>:54:23)
2020-02-20T04:43:26.8341791Z  +  pulumi:pulumi:Stack pulumify-pulumify-pulumi-docs-justin-purge creating     at Generator.next (<anonymous>)
2020-02-20T04:43:26.8342772Z  +  pulumi:pulumi:Stack pulumify-pulumify-pulumi-docs-justin-purge creating     at fulfilled (<anonymous>:11:58)
2020-02-20T04:43:26.8343814Z  +  pulumi:pulumi:Stack pulumify-pulumify-pulumi-docs-justin-purge creating     at processTicksAndRejections (internal/process/task_queues.js:86:5)
2020-02-20T04:43:26.8357568Z  +  pulumi-nodejs:dynamic:Resource content-syncer creating error: Invoking sync function 'arn:aws:lambda:us-east-1:894850187425:function:content-syncer-copyfunc-8c64fd3' failed [Unhandled]: "{\"errorMessage\": \"An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\", \"errorType\": \"NoSuchKey\", \"stackTrace\": [\"  File \\\"/var/task/index.py\\\", line 42, in handler\\n    archive_bytes = io.BytesIO(s3.meta.client.get_object(Bucket=bucket, Key=archive_key)['Body'].read())\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 357, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 661, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
2020-02-20T04:43:26.8359562Z  +  pulumi-nodejs:dynamic:Resource content-syncer **creating failed** error: Invoking sync function 'arn:aws:lambda:us-east-1:894850187425:function:content-syncer-copyfunc-8c64fd3' failed [Unhandled]: "{\"errorMessage\": \"An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\", \"errorType\": \"NoSuchKey\", \"stackTrace\": [\"  File \\\"/var/task/index.py\\\", line 42, in handler\\n    archive_bytes = io.BytesIO(s3.meta.client.get_object(Bucket=bucket, Key=archive_key)['Body'].read())\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 357, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 661, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
2020-02-20T04:43:26.9955277Z  +  pulumi:pulumi:Stack pulumify-pulumify-pulumi-docs-justin-purge creating error: update failed
2020-02-20T04:43:27.0318459Z  +  pulumi:pulumi:Stack pulumify-pulumify-pulumi-docs-justin-purge **creating failed** 1 error; 6 messages
2020-02-20T04:43:27.0319216Z  
2020-02-20T04:43:27.0319425Z Diagnostics:
2020-02-20T04:43:27.0320216Z   pulumi-nodejs:dynamic:Resource (content-syncer):
2020-02-20T04:43:27.0321342Z     error: Invoking sync function 'arn:aws:lambda:us-east-1:894850187425:function:content-syncer-copyfunc-8c64fd3' failed [Unhandled]: "{\"errorMessage\": \"An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\", \"errorType\": \"NoSuchKey\", \"stackTrace\": [\"  File \\\"/var/task/index.py\\\", line 42, in handler\\n    archive_bytes = io.BytesIO(s3.meta.client.get_object(Bucket=bucket, Key=archive_key)['Body'].read())\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 357, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 661, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
2020-02-20T04:43:27.0321596Z  
2020-02-20T04:43:27.0321959Z   pulumi:pulumi:Stack (pulumify-pulumify-pulumi-docs-justin-purge):
2020-02-20T04:43:27.0322110Z     (node:134) ExperimentalWarning: queueMicrotask() is experimental.
2020-02-20T04:43:27.0322241Z  
2020-02-20T04:43:27.0323337Z     Error: Invoking sync function 'arn:aws:lambda:us-east-1:894850187425:function:content-syncer-copyfunc-8c64fd3' failed [Unhandled]: "{\"errorMessage\": \"An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\", \"errorType\": \"NoSuchKey\", \"stackTrace\": [\"  File \\\"/var/task/index.py\\\", line 42, in handler\\n    archive_bytes = io.BytesIO(s3.meta.client.get_object(Bucket=bucket, Key=archive_key)['Body'].read())\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 357, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\", \"  File \\\"/var/task/botocore/client.py\\\", line 661, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
2020-02-20T04:43:27.0323719Z         at Object.<anonymous> (<anonymous>:54:23)
2020-02-20T04:43:27.0323860Z         at Generator.next (<anonymous>)
2020-02-20T04:43:27.0323989Z         at fulfilled (<anonymous>:11:58)
2020-02-20T04:43:27.0324128Z         at processTicksAndRejections (internal/process/task_queues.js:86:5)
2020-02-20T04:43:27.0324246Z  
2020-02-20T04:43:27.0324361Z     error: update failed
```

@cnunciato, @stack72, any ideas since we made some changes here today?

Note: If the fix involves tweaking the Python lambda code in https://github.com/pulumi/actions-pulumify/blob/master/infra/lambda/index.py, remember to run `./make.sh` to copy the changes into the `bin` directory.

**Comment by justinvp** [comment]
Sounds like this will resolve itself tomorrow? https://github.com/pulumi/docs/pull/2485#pullrequestreview-361634178

**Comment by stack72** [comment]
@justinvp / @cnunciato this feels like it's much better now - the pulumify builds  have been working recently right?

**Comment by cnunciato** [comment]
Yep, they have. I'll go ahead and close. Thanks @stack72!
